version: '3'
services:
    redis:
        container_name: 'redis'
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6380:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
        networks:
            - app-network
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - app-network
    elasticsearch:
        image: elasticsearch:8.8.0
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        networks:
            - app-network
    api:
        build:
            context: .
        container_name: desafio-backend-konsi
        ports:
            - '${PORT}:${PORT}'
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - CONSULTA_API_USERNAME=${CONSULTA_API_USERNAME}
            - CONSULTA_API_PASSWORD=${CONSULTA_API_PASSWORD}
            - CONSULTA_API_URL=${CONSULTA_API_URL}
            - RABBIT_URL=${RABBIT_URL}
            - ELASTIC_NODE_URL=${ELASTIC_NODE_URL}
            - REDIS_URL=${REDIS_URL}
            - ENABLE_CONSUMER=${ENABLE_CONSUMER}
        links:
            - rabbitmq
        depends_on:
            - rabbitmq
            - redis
            - elasticsearch
        networks:
            - app-network
volumes:
    cache:
networks:
    app-network:
        driver: bridge
